### PR TITLE
fix: change replace to equals

### LINKED ISSUE #3: yard-js execution error
command: **bundle exec yard -m markdown -e lib/yard-js.rb**
-
### _**ERROR**_:
bundler: failed to load command: yard (/home//.gem/ruby/2.3.0/bin/yard)
RuntimeError: can't modify frozen String
/home//workspace/sdk-documentation/yard//src/lib/yard-js/core_ext/yard.rb:9:in` replace' /home/****/workspace/sdk-documentation/yard/****/src/lib/yard-js/core_ext/yard.rb:9:in <top (required)>'
/home//workspace/sdk-documentation/yard//src/lib/yard-js/plugin.rb:1:in require_relative' /home/****/workspace/sdk-documentation/yard/****/src/lib/yard-js/plugin.rb:1:in <top (required)>'
lib/yard-js.rb:2:in require_relative' lib/yard-js.rb:2:in <top (required)>'
/home//.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:70:in load' /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:70:in load_script'
/home//.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:28:in block in common_options' /usr/local/lib/ruby/2.3.0/optparse.rb:1571:in block in parse_in_order'
/usr/local/lib/ruby/2.3.0/optparse.rb:1527:in catch' /usr/local/lib/ruby/2.3.0/optparse.rb:1527:in parse_in_order'
/usr/local/lib/ruby/2.3.0/optparse.rb:1521:in order!' /usr/local/lib/ruby/2.3.0/optparse.rb:1613:in permute!'
/usr/local/lib/ruby/2.3.0/optparse.rb:1635:in parse!' /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:56:in parse_options'
/home//.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/yardoc.rb:535:in optparse' /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/yardopts_command.rb:42:in parse_arguments'
/home//.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/yardoc.rb:292:in parse_arguments' /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/yardoc.rb:248:in run'
/home//.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:14:in run' /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command_parser.rb:72:in run'
/home//.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command_parser.rb:54:in run' /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/bin/yard:13:in <top (required)>'
/home//.gem/ruby/2.3.0/bin/yard:23:in load' /home/****/.gem/ruby/2.3.0/bin/yard:23:in <top (required)>'

### PR DESCRIPTION
**Pull request by trivikr**
Fixes: https://github.com/lsegal/yard-js/issues/3
Verified fix in https://github.com/aws/aws-sdk-js/pull/3871

### CODE REVIEW

**Comment by mullermp** [comment]
@lsegal Mind merging this? :D

**Comment by lsegal** [comment]
Done!

**Comment by trivikr** [comment]
Thank you @lsegal for merging this fix!
Can you release a new version of yard-js on RubyGems (say `v0.2.0`) which contains this fix?

**Comment by lsegal** [comment]
@trivikr given that this library is rarely used from other Ruby code, yard-js rubygem releases are not widely supported. You should be able to use yard-js from a Gemfile until a release is made available (if at all). To be honest, this library is not really maintained anymore and does not actively support Ruby 2.6+.

**Pull request merged**
